# The whole assignment is about `Riyadh Marathon Results.csv`. make sure to upload it to the notebook

#Task 1 — Load the Dataset

1. Import pandas

2. Load CSV

3. Display first 5 rows

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Riyadh Marathon Results.csv')
df.head()

,Unnamed: 0,Rank,Gender Rank,Name,Gender,Category,Nationality,Gun Time,Chip Time,Speed,Pace,Distance
0,0,46 / 2285,1 / 761,6b848725-e44d-42d8-a278-ae67faa9cb80,Female,10KM RUN,[img:flags/SA.gif],00:42:59.556,00:42:57.505,13.9 Km/Hr,4:17 min/km,10 KM
1,1,53 / 2285,2 / 761,6b848725-e44d-42d8-a278-ae67faa9cb80,Female,10KM RUN,[img:flags/CZ.gif],00:43:28.175,00:43:24.774,13.8 Km/Hr,4:20 min/km,10 KM
2,2,55 / 2285,3 / 761,6b848725-e44d-42d8-a278-ae67faa9cb80,Female,10KM RUN,[img:flags/SA.gif],00:44:00.251,00:43:56.317,13.6 Km/Hr,4:23 min/km,10 KM
3,3,88 / 2285,4 / 761,6b848725-e44d-42d8-a278-ae67faa9cb80,Female,10KM RUN,[img:flags/MA.gif],00:48:28.115,00:48:22.908,12.4 Km/Hr,4:50 min/km,10 KM
4,4,93 / 2285,5 / 761,6b848725-e44d-42d8-a278-ae67faa9cb80,Female,10KM RUN,[img:flags/SA.gif],00:58:37.753,00:48:27.714,12.3 Km/Hr,4:50 min/km,10 KM

#Task 2 — Basic Structure

1. Print dataset shape

2. How many rows?

3. How many columns?

In [ ]:
df.shape

(6397, 12)

#Task 3 — Column Analysis

1. List all column names

2. What do they represent?

In [ ]:
df.columns

Index(['Unnamed: 0', 'Rank', 'Gender Rank', 'Name', 'Gender', 'Category',
       'Nationality', 'Gun Time', 'Chip Time', 'Speed', 'Pace', 'Distance'],
      dtype='object')

#Task 4 — Data Types

1. Use `df.info()`

2. Identify:

* Numerical columns

* Categorical columns

* Boolean columns (if any)

In [ ]:
df.info()
# numerical columns: Unnamed: 0 int
# categorical columns: Rank,	Gender, Rank,	Name,	Gender,	Category,	Nationality,	Gun Time,	Chip Time,	Speed	Pace,	Distance
# boolean columns: none

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6397 entries, 0 to 6396
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   6397 non-null   int64
 1   Rank         6397 non-null   object
 2   Gender Rank  6397 non-null   object
 3   Name         6397 non-null   object
 4   Gender       6397 non-null   object
 5   Category     6397 non-null   object
 6   Nationality  6085 non-null   object
 7   Gun Time     6397 non-null   object
 8   Chip Time    6227 non-null   object
 9   Speed        6227 non-null   object
 10  Pace         6227 non-null   object
 11  Distance     6397 non-null   object
dtypes: int64(1), object(11)
memory usage: 599.8+ KB

# Task 5 — Target Identification

* Choose a possible target

* Is the problem classification or regression?

* Explain why.

In [ ]:
# Target: Speed
# Problem type: Regression
# Explanation: We want to predict a runner's speed
# based on features such as gender and distance.
# Since speed is a continuous numerical value,
# this is a regression problem.

Gender  Speed
Female  5.1 Km/Hr     72
        6.1 Km/Hr     67
        5.2 Km/Hr     59
        5.7 Km/Hr     59
        5.4 Km/Hr     57
                      ..
Male    23.4 Km/Hr     1
        23.7 Km/Hr     1
        24.5 Km/Hr     1
        28.2 Km/Hr     1
        33.1 Km/Hr     1
Name: count, Length: 304, dtype: int64

#Task 6 — Summary Statistics

1. Use `df.describe()`

2. Identify one interesting observation

In [ ]:
df.describe()
# only info about column 'unnamed' -which is probably an index column- is shown since it's the only numerical column

        Unnamed: 0
count  6397.000000
mean    537.356886
std     381.548171
min       0.000000
25%     213.000000
50%     477.000000
75%     797.000000
max    1578.000000

#Task 7 — Short Written Insight

1. Write 5–7 lines answering:

2. What does this dataset represent?

3. What could be the business problem?

4. What type of ML problem is this?

5. What should we check next?

In [ ]:
# 1. This dataset contains the results of Riyadh Marathon participants.
#    It includes information such as gender, nationality, distance, speed, pace, and finishing times.
# 2. A possible business problem is predicting runners' performance based on their characteristics.
# 3. This could be a regression problem if we predict speed.
# 4. We should check for missing values and duplicates.
#    We should also convert numerical information stored as strings into appropriate numerical data types.